#pragma once

int hello();
int IntegerTypes();
int VariableDeclaration();
int CharacterConstants();
int DefiningConstants();
int StaticStorageClass();
void ExternStorageClass();
int InfiniteLoop();
int max(int num1, int num2);
int CallingFunctionMax();
int LocalVariables();
int GlobalVariables();
int Arrays();
int Pointers();
int UsePointers();
int NullPointers();
int StringsGreetings();
int StringsFuncs();
int Structures();
void printBook_1(struct Books book);
void printBook_2(struct Books* book);
int Unions();
int BitFields();
int BitFieldDeclaration();
int typedefC();
int defineC();
int InputOutput_1();
int InputOutput_2();
int InputOutput_3();
void WrittingFile();
int PreprocesorsMacros();
int PreprocessorsStringize();
int PreprocessorsTokenPasting();
int PreprocessorsDefined();
int PreprocessorsParameterized();
int BasicTypeCasting();
int IntegerPromotion();
int ArithmeticConversion();
int FileError();
int ZeroErrors();
int ProgramExitStatus();
unsigned long long int factorial(unsigned int i);
int factorialTest();
int fibonacci(int i);
int fibonacciTest();
int va_average(int num, ...);
int va_averageTest();
int AllocatingMemoryDynamically();
int ResizingaReleasingMemory();